spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pms_db
    username: pms_user
    password: pms_password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: AuthServicePool

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          min-idle: 2
          max-idle: 10
          max-active: 20

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: openid,email,profile
            redirect-uri: "{baseUrl}/api/v1/auth/google/callback"

server:
  port: 8081
  servlet:
    context-path: /api/v1
  error:
    include-message: never
    include-stacktrace: never

jwt:
  secret: ${JWT_SECRET:c2VjcmV0S2V5Rm9yTG9jYWxEZXZPbmx5RG9Ob3RVc2VJblByb2R1Y3Rpb24=}
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

app:
  trial-period-days: 30
  max-failed-login-attempts: 5
  account-lock-duration-minutes: 30
  max-concurrent-sessions: 3
  password-history-count: 5
  otp-expiry-minutes: 10
  invite-expiry-hours: 48
