spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pms_db
    username: pms_user
    password: pms_password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: AuthServicePool

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          min-idle: 2
          max-idle: 10
          max-active: 20

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  servlet:
    context-path: /api/v1
  error:
    include-message: never
    include-stacktrace: never

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

app:
  trial-period-days: 30
  max-failed-login-attempts: 5
  account-lock-duration-minutes: 30
  max-concurrent-sessions: 3
  password-history-count: 5
  otp-expiry-minutes: 10
  invite-expiry-hours: 48