spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pms_db
    username: pms_user
    password: pms_password
    hikari:
      pool-name: NotificationServicePool
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085
  servlet:
    context-path: /api/v1